title: Slip Style Guide
logo: assets/img/slipLogoFull.svg
description: Powerful, Seamless, Easy Issue Tracking
show_downloads: false
google_analytics:
baseurl: /tchnclcm300styleguide-kkpudi
theme: jekyll-theme-minimal
